#!/bin/bash
echo $(($(echo "obase=8; $(echo "ibase=5; $(echo $WATER | tr 'water' '01234')" | bc)" | bc)+$(echo "obase=8; $(echo "ibase=5; $(echo $STIR | tr 'stir.' '01234')" | bc)" | bc))) | tr '01234567' 'bestchol'
